name: macos test plots build
on: [push]


jobs:
  plot_target:
    runs-on: macos-10.15 
    steps:
      - name: install dvc
        run: brew install dvc
      - name: version
        run: dvc version
      - name: run script
        run: ./script.sh

