name: macos test plots build
on: [push]


jobs:
  plot_target:
    runs-on: macos-10.15 
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: 3.7
      - name: install dvc
        run: pip install dvc==1.7.9
      - name: version
        run: dvc version
      - uses: actions/checkout@v2
      - name: run script
        run: ./script.sh

